import assert from 'node:assert/strict';
import {parseCsv,parseDate,parseAmount,categorise,fingerprint,totals,blankState,demoState,nextDue,currentMonth,upgradeState,reviewGroups,applyGroupCategory,csvFormatKey,suggestBudgets,saveMonthBudgets,budgetsForMonth,runwayEstimate,categoryName} from '../lib/ledger.ts';
let count=0;
function test(name,fn){fn();count++;console.log('PASS '+name)}
test('Quoted commas, embedded newlines, escaped quotes, CRLF and BOM',()=>{assert.deepEqual(parseCsv('\uFEFFDate,Description,Amount\r\n29/09/2026,"A, B\nC ""D""",-12.50\r\n'),[['Date','Description','Amount'],['29/09/2026','A, B\nC "D"','-12.50']])});
test('Semicolon CSV and headerless input',()=>{assert.deepEqual(parseCsv('29/09/2026;Tesco;-10\n'),[['29/09/2026','Tesco','-10']])});
test('Broken quotes rejected',()=>assert.throws(()=>parseCsv('a,"b,c\n')));
test('Impossible dates rejected, leap day valid, date order explicit',()=>{assert.equal(parseDate('31/02/2026','DMY'),null);assert.equal(parseDate('29/02/2024','DMY'),'2024-02-29');assert.equal(parseDate('09/10/26','DMY'),'2026-10-09');assert.equal(parseDate('09/10/26','MDY'),'2026-09-10');assert.equal(parseDate('2026-13-01','DMY'),null)});
test('Money formats and empty values',()=>{assert.equal(parseAmount('£1,234.50'),1234.5);assert.equal(parseAmount('(12.50)'),-12.5);assert.ok(Number.isNaN(parseAmount('')))});
test('Recognised merchants skip review; refunds stay distinct; rules take priority',()=>{assert.deepEqual(categorise('Tesco',-20,[]),{category:'Groceries',review:false,reviewReasons:[]});assert.deepEqual(categorise('Tesco refund',20,[]).reviewReasons,['refund']);assert.deepEqual(categorise('Campus café',-5,[{id:'1',merchant:'Campus',category:'Eating out'}]),{category:'Eating out',review:false,reviewReasons:[]});assert.equal(categorise('Boots pharmacy',-12,[]).category,'Health');assert.equal(categorise('Octopus Energy',-30,[]).category,'Utilities')});
test('Duplicate keys normalise description and preserve sign',()=>{assert.equal(fingerprint({date:'2026-09-29',merchant:' TESCO  London ',amount:-10}),fingerprint({date:'2026-09-29',merchant:'tesco london',amount:-10}));assert.notEqual(fingerprint({date:'2026-09-29',merchant:'Tesco',amount:10}),fingerprint({date:'2026-09-29',merchant:'Tesco',amount:-10}))});
test('Savings and transfers do not count as spending; bills reserved once',()=>{const s=demoState();const t=totals(s,currentMonth());assert.equal(Math.round(t.spent*100),112123);assert.equal(t.saved,150);assert.equal(t.unpaid,23);assert.equal(Math.round(t.available*100),30577)});
test('Linking an imported bill does not create more spending',()=>{const s=blankState();s.income=100;s.transactions=[{id:'p',date:'2026-09-29',merchant:'Broadband',amount:-23,category:'Rent & bills',review:false,source:'Manual'}];s.bills=[{id:'b',date:'2026-09-30',name:'Broadband',amount:23,recurrence:'monthly',payments:[]}];const before=totals(s,'2026-09');s.bills[0].payments.push({date:'2026-09-29',transactionId:'p'});const after=totals(s,'2026-09');assert.equal(after.spent,before.spent);assert.equal(after.unpaid,0);assert.equal(after.available,77)});
test('Month-end recurrence clamps dates and preserves local day',()=>{assert.equal(nextDue('2026-01-31','monthly'),'2026-02-28');assert.equal(nextDue('2024-02-29','yearly'),'2025-02-28');assert.equal(nextDue('2026-09-29','weekly'),'2026-10-06')});

test('Legacy workspace upgrades without losing records or budget history',()=>{const s=demoState();const oldId=s.transactions[0].id;const u=upgradeState(s);assert.equal(u.version,2);assert.equal(u.transactions[0].id,oldId);assert.equal(u.transactions.find(t=>t.review)?.reviewReasons[0],'category');assert.deepEqual(budgetsForMonth(u,currentMonth()),s.budgets)});
test('One merchant decision updates unresolved entries only and remembers direction',()=>{const s=blankState();s.transactions=[{id:'a',date:'2026-09-01',merchant:'SQ * Campus Café',amount:-5,category:'Other',review:true,reviewReasons:['category'],source:'x'},{id:'b',date:'2026-09-02',merchant:'Campus Cafe',amount:-6,category:'Other',review:true,reviewReasons:['category'],source:'x'},{id:'c',date:'2026-09-03',merchant:'Campus Café',amount:-7,category:'Shopping',review:false,reviewReasons:[],source:'x'}];assert.equal(reviewGroups(s)[0].transactions.length,2);const n=applyGroupCategory(s,reviewGroups(s)[0].key,'Eating out',true);assert.equal(n.transactions.filter(t=>t.category==='Eating out').length,2);assert.equal(n.transactions[2].category,'Shopping');assert.equal(n.rules[0].direction,-1)});
test('Remembered CSV format identifies header and headerless layouts',()=>{assert.equal(csvFormatKey([['Date','Description','Amount'],['01/10/2026','Tesco','-10']],true),csvFormatKey([[' date ','description','amount'],['02/10/2026','Shop','-5']],true));assert.equal(csvFormatKey([['01/10/2026','Tesco','-10']],false),csvFormatKey([['02/10/2026','Shop','-5']],false))});
test('Monthly budget changes preserve a past month and custom names use stable IDs',()=>{let s=blankState();s.categoryDefs=[{id:'custom-1',name:'Books',custom:true}];s.budgets=[{category:'custom-1',limit:40}];s=saveMonthBudgets(s,'2026-09',[{category:'custom-1',limit:40}]);s=saveMonthBudgets(s,'2026-10',[{category:'custom-1',limit:80}]);s.categoryDefs[0].name='Course books';assert.equal(categoryName(s,'custom-1'),'Course books');assert.equal(budgetsForMonth(s,'2026-09')[0].limit,40);assert.equal(budgetsForMonth(s,'2026-10')[0].limit,80)});
test('Budget suggestions use completed transaction history',()=>{const s=blankState();s.transactions=Array.from({length:12},(_,i)=>({id:String(i),date:`2026-09-${String(i+1).padStart(2,'0')}`,merchant:'Tesco',amount:-10,category:'Groceries',review:false,source:'x'}));const x=suggestBudgets(s,'2026-10');assert.match(x.basis,/2026-09/);assert.equal(x.budgets.find(b=>b.category==='Groceries')?.limit,120)});
test('Runway deducts only unpaid upcoming bills and remaining savings',()=>{const s=blankState();s.savings=50;s.runway={mode:'manual',availableNow:500,recordedAt:'2026-10-02',nextPaymentDate:'2026-10-16'};s.bills=[{id:'bill',name:'Rent',amount:100,date:'2026-10-10',recurrence:'once',payments:[]}];const r=runwayEstimate(s,'2026-10-02');assert.equal(r?.available,350);assert.equal(r?.weekly,175);s.runway={mode:'estimate',estimateFrom:'2026-10-01',nextPaymentDate:'2026-10-16'};s.transactions=[{id:'in',date:'2026-10-01',merchant:'Pay',amount:500,category:'Income',review:false,source:'x'},{id:'out',date:'2026-10-02',merchant:'Tesco',amount:-25,category:'Groceries',review:false,source:'x'}];assert.equal(runwayEstimate(s,'2026-10-02')?.available,325)});
console.log(`${count} domain checks passed`);
